//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazılım_Yapımı_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int Urunid { get; set; }
        public string URUNAD { get; set; }
        public Nullable<double> URUNFIYAT { get; set; }
        public Nullable<double> URUNSTOK { get; set; }
        public Nullable<int> KULLANICI { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
