//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazılım_Yapımı_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_admin
    {
        public byte adminid { get; set; }
        public string adminisim { get; set; }
        public string sifre { get; set; }
    }
}
