//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazılım_Yapımı_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Emir
    {
        public int EmirId { get; set; }
        public string EmirUrun { get; set; }
        public Nullable<double> EmirKilo { get; set; }
        public Nullable<double> EmirFiyat { get; set; }
        public string EmirTarih { get; set; }
        public Nullable<bool> EmirDurum { get; set; }
        public Nullable<int> EmirUser { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
